/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://activeplay.games',
  generateRobotsTxt: false,
  outDir: 'public',
  changefreq: 'weekly',
  priority: 0.7,
  additionalPaths: async () => [
    { loc: '/', changefreq: 'daily', priority: 1.0 },
    { loc: '/ps-plus-essential', changefreq: 'weekly', priority: 0.9 },
    { loc: '/ps-plus-extra', changefreq: 'weekly', priority: 0.9 },
    { loc: '/ps-plus-deluxe', changefreq: 'weekly', priority: 0.9 },
    { loc: '/ea-play', changefreq: 'weekly', priority: 0.9 },
    { loc: '/igrovaya-valyuta', changefreq: 'weekly', priority: 0.8 },
    { loc: '/news', changefreq: 'daily', priority: 0.8 },
    { loc: '/guides', changefreq: 'weekly', priority: 0.8 },
    // News articles
    { loc: '/news/sony-anonsirovala-ps6-specifikacii', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/ps-plus-april-2026-igry', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/obzor-ghost-of-yotei', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/intervyu-razrabotchik-astro-bot', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/xbox-game-pass-mart-2026-dobavleniya', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/podcast-itogi-gdc-2026', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/obzor-final-fantasy-7-rebirth-pc', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/days-of-play-2026-daty-skidki', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/video-sravnenie-ps-plus-xbox-game-pass-2026', changefreq: 'monthly', priority: 0.6 },
    { loc: '/news/nintendo-switch-2-cena-data', changefreq: 'monthly', priority: 0.6 },
    // Guide articles
    { loc: '/guides/kak-kupit-ps-plus-iz-rossii', changefreq: 'monthly', priority: 0.7 },
    { loc: '/guides/kak-sozdat-tureckij-akkaunt-psn', changefreq: 'monthly', priority: 0.7 },
    { loc: '/guides/xbox-game-pass-polnyj-gajd', changefreq: 'monthly', priority: 0.7 },
    { loc: '/guides/oplata-cherez-sbp-karta-mir', changefreq: 'monthly', priority: 0.7 },
    { loc: '/guides/kak-razdat-ps-plus-na-neskolko-akkauntov', changefreq: 'monthly', priority: 0.7 },
    { loc: '/guides/faq-activeplay', changefreq: 'monthly', priority: 0.7 },
  ],
}
